# Change these first
owner: alex602022 # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: onmid
    url: https://onmid.net
  - name: my nav
    url: https://nav.onmid.net
  - name: my web3 nav
    url: https://wnav.onmid.net
  - name: chat
    url: https://chat.onmid.net
  - name: wiki
    url: http://43.142.236.225:890/
  - name: onmid.montaigne.io
    url: https://onmid.montaigne.io/

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: alex Upptime
  introTitle: onmid monitor
  introMessage: 
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
